### ISSUE TITLE
SQLAlchemyError에 대한 status code 통일 필요

### ISSUE THREAD

**Issue by Orb-H** [SWE3022-42-team9/skktudy-server#27]
현재 코드 상 DB의 작동 상 오류에 대한 status code가 크게 두 가지 경우 존재합니다.

1. 제가 구현한 케이스로 status code 503과 함께 `SQLAlchemyError._message()`를 메시지로 반환합니다.
2. 재현님이 구현한 케이스로 status code 500과 함께 `str(SQLAlchemyError)`를 메시지로 반환합니다.

일관된 response를 만들기 위해서 status code와 메시지를 한 가지로 통일하는 작업이 필요해보입니다.

**Comment by legionary7931** [comment]
SQLAlchemyError._message()로 반환하는 것과 str(SQLAlchemyError)로 반환하는 것이 차이가 있나요?

**Comment by Orb-H** [comment]
조금 차이가 있다고 합니다. 찾아보니 e._message()보다는 str(e)를 사용하는 것이 좋다고 하고, DB 자체 오류는 e.orig를 사용하는 방법도 있다고 합니다.

**Comment by Orb-H** [comment]
분명 같은 DB 오류인데 status code를 2가지 사용하고 있는 것이 클라이언트 입장에서 불편할 것이라 생각해서 통일 제안합니다.
